name: data-lit
dependencies:
  - pip
  - pip:
    - arxiv
    - beautifulsoup4
    - pylatexenc
    - nltk
    - enchant
    - matplotlib
    - scikit-learn
    - numpy
    - pandas
    - PyDictionary
